"""A simulated field, for the parts of the forecast reality will not score.

Overall ownership can be backtested against real data, and is. Captaincy share
cannot: no public time series of per-player captaincy share exists. The FPL API
publishes only ``events[].most_captained`` -- one player id per gameweek -- and
the archived community datasets carry ownership and transfers but no armband.

So the captaincy number in this package's report is measured against a
simulated field, and is labelled that way everywhere it appears. The simulation
is built to make that measurement mean something rather than nothing:

* The managers' captain rule is **not** the model's functional form. Managers
  maximise a latent private valuation; the model fits a logit on ownership and
  price. The model cannot recover the answer by construction.
* The latent appeal is only *correlated* with price, which is all the model can
  see. Price is a proxy, and a deliberately imperfect one, exactly as in reality.
* Managers are heterogeneous: template followers with little private noise sit
  alongside contrarians with a lot.
* Ownership fed to the model is the ownership the simulation *realised*, not the
  ownership it was asked for, so the model is never handed a consistent pair
  that reality would not have produced.

What this does and does not establish: it tests whether the functional form and
the concentration parameter can recover a captaincy distribution generated by a
different process. It does not establish that real managers behave this way.
The real number arrives after the first deadline, from
:class:`~fpl_edge.models.ownership.elite.ElitePicksSampler`.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True, slots=True)
class SimulatedField:
    ownership: np.ndarray       # realised share owning each player
    start_share: np.ndarray     # realised share starting each player
    captaincy: np.ndarray       # realised share captaining each player
    n_managers: int

    def check(self) -> None:
        if abs(self.captaincy.sum() - 1.0) > 1e-9:
            raise ValueError("simulated captaincy must sum to 1: one armband per manager")


def simulate_field(
    target_ownership: np.ndarray,
    price_tenths: np.ndarray,
    position: np.ndarray,
    *,
    n_managers: int = 4000,
    seed: int = 0,
    appeal_noise: float = 1.4,
    herding: float = 0.55,
    squad_size: int = 15,
    starting_xi: int = 11,
) -> SimulatedField:
    """Draw a field of managers and record what they own, start and captain.

    ``appeal_noise`` is the standard deviation of the gap between a player's
    latent captaincy appeal and the price signal the model can see. Raising it
    makes price a worse proxy and the model's task harder.
    """
    rng = np.random.default_rng(seed)
    own = np.clip(np.asarray(target_ownership, dtype=float), 1e-9, 1.0)
    price_m = np.asarray(price_tenths, dtype=float) / 10.0
    pos = np.asarray(position, dtype=int)
    n = own.size

    # Latent appeal: price plus structural noise the model cannot observe, and a
    # hard penalty for keepers and defenders that the model must learn to match.
    latent = price_m + rng.normal(0.0, appeal_noise, size=n)
    latent = latent + np.where(pos == 1, -6.0, np.where(pos == 2, -3.0, 0.0))

    # Squads: Gumbel top-k gives a weighted sample without replacement per
    # manager, vectorised over the whole field.
    logw = np.log(own)[None, :]
    gumbel = rng.gumbel(size=(n_managers, n))
    order = np.argsort(-(logw + gumbel), axis=1)
    squad = order[:, :squad_size]
    xi = squad[:, :starting_xi]  # the XI is the top of the same ordering

    owned_counts = np.bincount(squad.ravel(), minlength=n)
    start_counts = np.bincount(xi.ravel(), minlength=n)

    # Captain: heterogeneous private noise plus a herding pull toward the
    # template. Sophisticated managers trust their own read; the rest follow.
    sigma = rng.gamma(shape=2.0, scale=0.7, size=n_managers)[:, None]
    value = (
        latent[xi]
        + sigma * rng.normal(size=xi.shape)
        + herding * np.log(own)[xi]
    )
    captains = xi[np.arange(n_managers), np.argmax(value, axis=1)]
    cap_counts = np.bincount(captains, minlength=n)

    field = SimulatedField(
        ownership=owned_counts / n_managers,
        start_share=start_counts / n_managers,
        captaincy=cap_counts / n_managers,
        n_managers=n_managers,
    )
    field.check()
    return field
