"""The bias probes: do they find what is there, and stay quiet about what is not?

Both halves are tested, and the second half is the one that matters. A probe that
fires on planted bias proves only that it is sensitive. A bias report is only
worth reading if it also declines to find anything in a null sample -- otherwise
it is a horoscope with p-values, and the user would be right to ignore it.

The planted samples are generated by submitting real messages through the real
inbox, so these tests exercise parsing, context capture and the verdict on every
idea as well as the statistics.
"""

from __future__ import annotations

import datetime as dt

import pytest

from fpl_edge.interfaces.bias import MIN_OBSERVATIONS, review
from fpl_edge.interfaces.inbox import IdeaInbox
from fpl_edge.interfaces.testing import SEASON, plant_ideas, seed_warehouse
from fpl_edge.interfaces.tracking import track
from fpl_edge.store import Warehouse

UTC = dt.timezone.utc

#: Mid-September 2026: four gameweeks are in the books, so form, venue and haul
#: context all exist. Ideas planted here settle well before December.
PLANT_AT = dt.datetime(2026, 9, 15, 20, 0, tzinfo=UTC)
SETTLE_AT = dt.datetime(2026, 12, 20, 12, 0, tzinfo=UTC)


def _history(tmp_path, *, biased: bool, n: int = 40) -> Warehouse:
    wh = seed_warehouse(tmp_path / f"{biased}.duckdb", n_gws=16, finished_gws=14)
    inbox = IdeaInbox(wh)
    planted = plant_ideas(inbox, n=n, when=PLANT_AT, biased=biased)
    assert planted.submitted >= MIN_OBSERVATIONS, "fixture must clear the evidence floor"
    track(wh, season=SEASON, now=SETTLE_AT)
    return wh


@pytest.fixture(scope="module")
def biased(tmp_path_factory) -> Warehouse:
    return _history(tmp_path_factory.mktemp("biased"), biased=True)


@pytest.fixture(scope="module")
def null(tmp_path_factory) -> Warehouse:
    return _history(tmp_path_factory.mktemp("null"), biased=False)


def _finding(wh: Warehouse, name: str):
    hit = [f for f in review(wh, season=SEASON).findings if f.name == name]
    assert hit, f"no probe named {name}"
    return hit[0]


# -- every probe must capture the data it needs ------------------------------


def test_every_idea_carries_its_submission_context(biased: Warehouse) -> None:
    """A silently dropped context row halves the power of every probe.

    This exists because it happened: a player who had never hauled carried
    ``gws_since_haul`` as float NaN rather than None, ``int(NaN)`` raised, and
    the exception was swallowed. Twelve of eighteen ideas lost their context with
    no visible symptom other than a suspiciously small n.
    """
    n_ideas = int(biased.sql("SELECT count(*) n FROM idea").iloc[0]["n"])
    n_context = int(biased.sql("SELECT count(*) n FROM idea_context").iloc[0]["n"])
    assert n_ideas > 0
    assert n_context == n_ideas


# -- the probes find planted bias --------------------------------------------


def test_form_chasing_is_detected_when_planted(biased: Warehouse) -> None:
    f = _finding(biased, "form_chasing")
    assert f.n >= MIN_OBSERVATIONS
    assert f.observed is not None and f.observed > 0.6  # picks sit high in the form distribution
    assert f.expected == 0.5                            # uniform under the null
    assert f.significant


def test_home_bias_is_detected_when_planted(biased: Warehouse) -> None:
    f = _finding(biased, "home_bias")
    assert f.observed is not None and f.expected is not None
    assert f.observed > f.expected
    assert f.significant


def test_club_affinity_is_detected_when_planted(biased: Warehouse) -> None:
    f = _finding(biased, "club_affinity")
    assert f.observed is not None and f.expected is not None
    assert f.observed > f.expected
    assert f.significant


# -- and stay quiet when there is nothing there ------------------------------


@pytest.mark.parametrize("name", ["form_chasing", "home_bias", "recency", "club_affinity"])
def test_no_probe_fires_on_an_unbiased_sample(null: Warehouse, name: str) -> None:
    f = _finding(null, name)
    assert not f.significant, f"{name} claimed a bias in a null sample: {f.verdict()}"


def test_the_null_sample_still_reports_its_numbers(null: Warehouse) -> None:
    """Not significant is not the same as no answer. The figures are still shown."""
    f = _finding(null, "club_affinity")
    assert f.n >= MIN_OBSERVATIONS
    assert f.observed is not None and f.expected is not None
    assert f.p_value is not None and f.p_adjusted is not None


# -- honesty about the base rate and about multiplicity ----------------------


def test_null_is_the_measured_population_not_a_convenient_constant(biased: Warehouse) -> None:
    """Home rate is not 0.5 in general; testing against 0.5 finds bias in the fixture list."""
    f = _finding(biased, "home_bias")
    assert f.expected is not None
    assert f.expected != 0.5
    assert 0.2 < f.expected < 0.8


def test_p_values_are_corrected_for_running_several_probes(null: Warehouse) -> None:
    rev = review(null, season=SEASON)
    live = [f for f in rev.findings if f.p_value is not None]
    assert len(live) >= 2
    for f in live:
        assert f.p_adjusted is not None
        assert f.p_adjusted >= f.p_value  # Holm never makes a p-value smaller


def test_small_samples_refuse_to_call_a_bias(tmp_path) -> None:
    wh = seed_warehouse(tmp_path / "few.duckdb", n_gws=16, finished_gws=14)
    inbox = IdeaInbox(wh)
    plant_ideas(inbox, n=4, when=PLANT_AT, biased=True)

    for f in review(wh, season=SEASON).findings:
        if 0 < f.n < MIN_OBSERVATIONS:
            assert not f.has_evidence
            assert not f.significant
            assert "NOT ENOUGH EVIDENCE" in f.verdict()


def test_preseason_review_says_what_it_cannot_know(tmp_path) -> None:
    """On 2026-08-18 no gameweek has finalised. Saying so beats imputing a form."""
    wh = seed_warehouse(tmp_path / "pre.duckdb", n_gws=16, finished_gws=0)
    inbox = IdeaInbox(wh)
    for text in ("I like Rashford", "Semenyo captain GW1", "sell Wood"):
        inbox.submit(text, source="test", now=dt.datetime(2026, 8, 18, 22, 50, tzinfo=UTC))

    rev = review(wh, season=SEASON)
    assert rev.scoreboard.n_total == 3
    assert rev.scoreboard.n_resolved == 0
    assert any("No idea has resolved yet" in c for c in rev.caveats)

    # Club affinity needs only a squad list, so it is the one probe that works
    # before a ball is kicked. The rest correctly report nothing.
    by_name = {f.name: f for f in rev.findings}
    assert by_name["club_affinity"].n == 3
    assert by_name["form_chasing"].n == 0
    assert "no data yet" in by_name["form_chasing"].verdict()


# -- the reason unacted ideas are tracked ------------------------------------


def test_review_separates_ideas_acted_on_from_ideas_skipped(biased: Warehouse) -> None:
    inbox = IdeaInbox(biased)
    for idea in inbox.registry.ideas(season=SEASON)[:6]:
        inbox.registry.mark_acted(idea.idea_id, when=SETTLE_AT)

    board = review(biased, season=SEASON).scoreboard
    assert board.acted_n > 0
    assert board.unacted_n > 0
    assert board.acted_n + board.unacted_n == sum(
        1 for i in inbox.registry.ideas(season=SEASON)
        if i.outcome is not None and str(i.outcome) != "push"
    )


def test_engine_calibration_is_measured_against_a_coin_flip(biased: Warehouse) -> None:
    board = review(biased, season=SEASON).scoreboard
    assert board.brier is not None
    assert board.baseline_brier == pytest.approx(
        0.25, abs=0.06
    ), "the always-50% baseline should sit near 0.25"


def test_prior_only_history_is_flagged_as_such(biased: Warehouse) -> None:
    """A Brier score from the price-rank prior must not read as an engine result."""
    rev = review(biased, season=SEASON)
    assert any("price-rank prior" in c for c in rev.caveats)
